apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-pod2
  template:
    metadata:
      labels:
        app: my-pod2
    spec:
      containers:
      - name: my-container2
        image: xyz673/web-pic:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-ld
  labels:
    app: my-pod2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-pod2
